name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      # Clone the repo
      - uses: actions/checkout@master
      # Run `npm run dev` to produce readme.md and others - install npm first
      - run: |
          NODE_ENV=development npm install
          npm run start
      # Remove npm and its dev packages
      - run: |
          ls
          rm -Rf node_modules
          ls
      # Prepare the release
      - run: |
          ls 
          composer install --no-dev
          npm install --production
          ls
      # Release to WordPress.org
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: user-export-with-their-meta-data
